"""The version ltvm reports, taken from git.

``git describe`` against the newest ``vMAJOR.MINOR`` tag gives the
version: ``v0.5-680-g71992dd`` is reported as ``0.5.680+71992dd888ab``,
the number of commits since the tag plus the commit hash.  A checkout
without the tag (shallow clone, tag not fetched) reports
``BASE_VERSION+<hash>``, and one without git just ``BASE_VERSION``.

A new minor or major version is a new annotated tag, with BASE_VERSION
moved to match; nothing in the tree changes per commit.

Stdlib only, and runnable as a script so ``.githooks/post-commit`` can
bake ``_build_info.py`` without starting ltvm::

    python3 ltvm_pkg/version_info.py <repo> <writer>
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

BASE_VERSION = "0.5"

# Release and artifact tags (qemu-9.2.2, rocky9-...) live in the same
# repository; only version tags may name the version.
TAG_GLOB = "v[0-9]*"


def _git(repo: Path, *args: str) -> str | None:
    if not (repo / ".git").exists():
        return None
    try:
        r = subprocess.run(
            ["git", "-C", str(repo), *args],
            capture_output=True,
            text=True,
            check=True,
            timeout=2,
        )
    except (subprocess.SubprocessError, OSError):
        return None
    return r.stdout.strip() or None


def version_from(short: str, describe: str) -> str:
    """The version for commit *short*, given its ``git describe --long``."""
    m = re.fullmatch(r"v(\d+\.\d+)-(\d+)-g[0-9a-f]+", describe.strip())
    if m:
        return f"{m.group(1)}.{m.group(2)}+{short}"
    return f"{BASE_VERSION}+{short}"


def describe_args() -> list[str]:
    return ["describe", "--match", TAG_GLOB, "--long", "HEAD"]


def git_version(repo: Path) -> tuple[str, str] | None:
    """(version, short hash) of *repo*'s HEAD, or None without git."""
    short = _git(repo, "rev-parse", "--short", "HEAD")
    if short is None:
        return None
    return version_from(short, _git(repo, *describe_args()) or ""), short


def build_info_text(writer: str, short: str, version: str) -> str:
    return (
        f'"""Auto-generated by {writer}. Do not edit or commit."""\n\n'
        f'BUILD_HASH = "{short}"\n'
        f'VERSION = "{version}"\n'
    )


def write_build_info(repo: Path, writer: str) -> bool:
    """Bake *repo*'s version into ltvm_pkg/_build_info.py."""
    got = git_version(repo)
    if got is None:
        return False
    version, short = got
    (repo / "ltvm_pkg" / "_build_info.py").write_text(
        build_info_text(writer, short, version)
    )
    return True


def read_baked_version(path: Path) -> str | None:
    """VERSION from a _build_info.py, read as text rather than imported.

    One baked before VERSION existed has only BUILD_HASH, and reads as
    BASE_VERSION+<hash>.
    """
    try:
        text = path.read_text()
    except OSError:
        return None
    m = re.search(r'^VERSION\s*=\s*["\']([^"\']+)["\']', text, re.M)
    if m:
        return m.group(1)
    m = re.search(r'^BUILD_HASH\s*=\s*["\']([^"\']+)["\']', text, re.M)
    return f"{BASE_VERSION}+{m.group(1)}" if m else None


if __name__ == "__main__":
    sys.exit(0 if write_build_info(Path(sys.argv[1]), sys.argv[2]) else 1)
